### ISSUE TITLE
Issue to start container

### ISSUE THREAD

**Issue by JochenKlenk** [pixeldublu/hassio#1]
Hi,

I was able to install the Add-on in HA and also to configure, but it looks like it not want to start.
Only log output I get is this.

s6-overlay-suexec: fatal: can only run as pid 1

Can you help.

Thanks

**Comment by pixeldublu** [comment]
Hi @JochenKlenk 

Modified the config according to this: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Can you have another test if this works now ?
